--- 
stages: 
  - 
    name: Build
    inputs: 
      - 
        type: git
        branch: master
    triggers: 
      - 
        type: commit
    jobs: 
      - 
        name: Build
        type: builder
        build_type: ant
        script: |-
            #!/bin/bash
            ant
        artifact_dir: output
  - 
    name: Deploy
    inputs: 
      - 
        type: job
        stage: Build
        job: Build
    triggers: 
      - 
        type: stage
    jobs: 
      - 
        name: dev
        type: deployer
        target: 
          app_name: sample-java-cloudant
          organization_guid: ${CF_ORGANIZATION_ID}
          space_guid: ${CF_SPACE_ID}
          url: ${CF_TARGET_URL}
